### ISSUE TITLE
Error in loading Perktutor in Slicer 4.10.2

### ISSUE THREAD

**Issue by carlos-luque** [PerkTutor/PerkTutor#67]
Hello all, 
   
    I am opening this issue, because we found this error in Slicer 4.10.2 when the extension Perktutor is installed.  The error is not generated in Slicer 4.10.1.  

-------------------------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/Users/CarlosLuque/AppData/Roaming/NA-MIC/Extensions-28257/PerkTutor/lib/Slicer-4.10/qt-scripted-modules/PythonMetricsCalculator.py", line 3, in <module>
    import urllib.request
ImportError: No module named request
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\CarlosLuque\AppData\Roaming\NA-MIC\Extensions-28257\PerkTutor\lib\Slicer-4.10\qt-scripted-modules\PythonMetricsCalculator.py", line 3, in <module>
    **import urllib.request**
ImportError: No module named request
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'PythonMetricsCalculator' is not defined
-----------------------------------------------------------------

I compared the different versions of PythonMetricsCalculator.py in Slicer 4.10.1 and Slicer 4.10.2 and the difference is in urllib.request.

Thanks in advances
Carlos Luque

**Comment by mholden8** [comment]
Thanks for the report. This seems to be related to the transition from Python 2 to Python 3 of Slicer. But I think it should be addressed by the pull request #65.

**Comment by mholden8** [comment]
Until pull request #66 is merged, it should work with the latest Slicer nightly.
